require('dotenv').config();
const MONGO_URL = process.env.MONGO_URL;
const PORT = process.env.PORT;
const JWT_SECRET = process.env.JWT_SECRET;
const JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN;
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
const ACCESS_TOKEN_EXPIRES_IN = process.env.ACCESS_TOKEN_EXPIRES_IN || '15m';
const REFRESH_TOKEN_EXPIRES_IN = process.env.REFRESH_TOKEN_EXPIRES_IN || '7d';
const OTEL_EXPORTER_OTLP_TRACES_ENDPOINT =
  process.env.OTEL_EXPORTER_OTLP_TRACES_ENDPOINT;
const OTEL_EXPORTER_OTLP_METRICS_ENDPOINT =
  process.env.OTEL_EXPORTER_OTLP_METRICS_ENDPOINT;
const NODE_ENV = process.env.NODE_ENV;
const LOG_LEVEL = process.env.LOG_LEVEL;
const DARAJA_CONSUMER_KEY = process.env.DARAJA_CONSUMER_KEY;
const DARAJA_CONSUMER_SECRET = process.env.DARAJA_CONSUMER_SECRET;
const DARAJA_CALLBACK_URL = process.env.DARAJA_CALLBACK_URL;
const DARAJA_PASS_KEY = process.env.DARAJA_PASS_KEY;
const BREVO_SMTP_USER = process.env.BREVO_SMTP_USER;
const BREVO_API_KEY = process.env.BREVO_API_KEY;
const CLIENT_URL = process.env.CLIENT_URL;
const TOKENS_VALID_FOR = process.env.TOKENS_VALID_FOR;

module.exports = {
  MONGO_URL,
  PORT,
  JWT_SECRET,
  JWT_EXPIRES_IN,
  REFRESH_TOKEN_EXPIRES_IN,
  ACCESS_TOKEN_EXPIRES_IN,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET,
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT,
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT,
  NODE_ENV,
  LOG_LEVEL,
  DARAJA_CONSUMER_KEY,
  DARAJA_CONSUMER_SECRET,
  DARAJA_CALLBACK_URL,
  DARAJA_PASS_KEY,
  BREVO_API_KEY,
  BREVO_SMTP_USER,
  CLIENT_URL,
  TOKENS_VALID_FOR
};
