openapi: 3.0.0
info:
  title: Event Ticketing API
  description: API for an event management system in node FullstackFusion EVent
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: Production version 1 server

paths:
  /status:
    get:
      responses:
        "200":
          desription: Server is working OK
          content:
            application/json:
              schema:
                type: string
        "500":
          desription: Something is definitely wrong with the server
